// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdpZ74-j-rIMnb8VYfEC88kEp1B6pJ6w',
    appId: '1:774373167152:web:79e59780bc5411b01c9df5',
    messagingSenderId: '774373167152',
    projectId: 'flutter-final-11a1d',
    authDomain: 'flutter-final-11a1d.firebaseapp.com',
    storageBucket: 'flutter-final-11a1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7JD32O1tuRZTuyE84OAsqajayA2Q_do',
    appId: '1:774373167152:android:79d9e1d3449dc10d1c9df5',
    messagingSenderId: '774373167152',
    projectId: 'flutter-final-11a1d',
    storageBucket: 'flutter-final-11a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJk5WT3pFdTR8AbjZNr4NAfIw5b6fANv8',
    appId: '1:774373167152:ios:65da761e8eebe2cb1c9df5',
    messagingSenderId: '774373167152',
    projectId: 'flutter-final-11a1d',
    storageBucket: 'flutter-final-11a1d.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJk5WT3pFdTR8AbjZNr4NAfIw5b6fANv8',
    appId: '1:774373167152:ios:65da761e8eebe2cb1c9df5',
    messagingSenderId: '774373167152',
    projectId: 'flutter-final-11a1d',
    storageBucket: 'flutter-final-11a1d.appspot.com',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCdpZ74-j-rIMnb8VYfEC88kEp1B6pJ6w',
    appId: '1:774373167152:web:8d4790ae436c84251c9df5',
    messagingSenderId: '774373167152',
    projectId: 'flutter-final-11a1d',
    authDomain: 'flutter-final-11a1d.firebaseapp.com',
    storageBucket: 'flutter-final-11a1d.appspot.com',
  );

}